services:
  - type: web
    name: v2dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: v2dashboard-db
          property: connectionString

databases:
  - name: v2dashboard-db
    databaseName: v2dashboard
    user: v2dashboard
    plan: free 