name = "v2dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAnApAQGqrW3L5m6aF8nen5hoB6ReUufQU"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "v2dash.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "v2dash"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "v2dash.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "431931037295"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:431931037295:web:bd406c083a08f072419f9a"

[[d1_databases]]
binding = "DB"
database_name = "v2dashboard-db"
database_id = "beea7aa3-d25d-4924-8afd-dc4d1e60d484" 