name = "v2dashboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "v2dashboard-db"
database_id = "beea7aa3-d25d-4924-8afd-dc4d1e60d484" 